@startuml
left to right direction
skinparam packageStyle rect

actor "Cliente (Paciente)" as Cliente
actor "Farmacêutico/Admin" as Admin

rectangle "App Farmácia Americana" {
  (Fazer Login/Cadastro Social) as (Login)
  (Consultar Catálogo e Busca) as (Busca)
  (Enviar Foto da Receita - OCR) as (OCR)
  (Tirar Dúvidas com IA - MIPs) as (Chat)
  (Finalizar Compra/Pagamento) as (Checkout)
  (Ver Histórico e Recompra) as (Historico)
  (Gerar Protocolo de Atendimento) as (Protocolo)
}

Cliente --> (Login)
Cliente --> (Busca)
Cliente --> (OCR)
Cliente --> (Chat)
Cliente --> (Checkout)
Cliente --> (Historico)

(OCR) ..> (Checkout) : <<include>>
(Chat) ..> (Protocolo) : <<include>>

(Protocolo) -- Admin : "Recebe Transbordo"
(OCR) -- Admin : "Valida Receita Controlada"
@enduml
